# Akash SDL (Stack Definition Language) File
# Deploy Node.js API + PostgreSQL Database
#
# Usage:
#   akash tx deployment create akash-deployment-api.yml --from wallet
#
# Required: Replace environment variables before deploying
#   - DATABASE_PASSWORD
#   - JWT_SECRET
#   - CORS_ORIGIN

version: "2.0"

services:
  api:
    # Docker image (replace with your image)
    image: ghcr.io/slopmachine/project-api:latest

    # Environment variables
    env:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:${DATABASE_PASSWORD}@db:5432/slopmachine
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - LOG_LEVEL=info

    # Expose HTTP port to the internet
    expose:
      - port: 3000
        as: 80
        to:
          - global: true
        accept:
          - slopmachine-api.example.com  # Replace with your custom domain

    # Dependencies (wait for db and redis to be ready)
    depends_on:
      - db
      - redis

  db:
    # PostgreSQL 15
    image: postgres:15-alpine

    # Environment variables
    env:
      - POSTGRES_DB=slopmachine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata

    # Expose PostgreSQL port (internal only, not to internet)
    expose:
      - port: 5432
        to:
          - service: api
          - service: db

    # Persistent storage configuration
    params:
      storage:
        data:
          mount: /var/lib/postgresql/data
          readOnly: false

  redis:
    # Redis 7
    image: redis:7-alpine

    # Redis configuration
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec

    # Expose Redis port (internal only)
    expose:
      - port: 6379
        to:
          - service: api

    # Persistent storage for Redis AOF
    params:
      storage:
        data:
          mount: /data
          readOnly: false

profiles:
  compute:
    # API service resources
    api:
      resources:
        cpu:
          units: 500m  # 0.5 vCPU
        memory:
          size: 1Gi    # 1 GB RAM
        storage:
          size: 512Mi  # 512 MB ephemeral storage

    # Database resources
    db:
      resources:
        cpu:
          units: 500m
        memory:
          size: 2Gi      # 2 GB RAM for PostgreSQL
        storage:
          data:
            size: 20Gi   # 20 GB persistent SSD
            attributes:
              persistent: true
              class: beta2  # SSD storage class

    # Redis resources
    redis:
      resources:
        cpu:
          units: 250m  # 0.25 vCPU
        memory:
          size: 512Mi  # 512 MB RAM
        storage:
          data:
            size: 5Gi    # 5 GB persistent storage
            attributes:
              persistent: true
              class: beta2

  placement:
    akash:
      # Pricing (in uAKT, 1 AKT = 1,000,000 uAKT)
      # 1000 uAKT ≈ $0.003/month (adjust based on market)
      pricing:
        api:
          denom: uakt
          amount: 1000
        db:
          denom: uakt
          amount: 2000
        redis:
          denom: uakt
          amount: 500

      attributes:
        # Provider attributes (optional filters)
        # Uncomment to require specific provider features
        # host: akash
        # region: us-west
        # tier: premium

      # Provider reputation requirements (optional)
      signedBy:
        # Only accept bids from audited providers
        # allOf:
        #   - akash1...  # Provider address
        anyOf: []

deployment:
  api:
    akash:
      profile: api
      count: 1

  db:
    akash:
      profile: db
      count: 1

  redis:
    akash:
      profile: redis
      count: 1
