[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
slop_machine = "DoxwpkBr2cNu2NYxWEZjopYtZwHzQPJuzZFasinMAXKm"

[programs.devnet]
slop_machine = "DoxwpkBr2cNu2NYxWEZjopYtZwHzQPJuzZFasinMAXKm"

[programs.mainnet]
slop_machine = "DoxwpkBr2cNu2NYxWEZjopYtZwHzQPJuzZFasinMAXKm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[provider.devnet]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[provider.mainnet]
cluster = "${HELIUS_RPC_URL}"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
